//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuthTLSConsoleApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OAuthTLSConsoleApplication.ServiceReference1.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OAuthTLSConsoleApplication.ServiceReference1.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OAuthTLSConsoleApplication.ServiceReference1.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OAuthTLSConsoleApplication.ServiceReference1.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMValidationContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMValidationContract : OAuthTLSConsoleApplication.ServiceReference1.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mainAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transactionDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                if ((object.ReferenceEquals(this.centerField, value) != true)) {
                    this.centerField = value;
                    this.RaisePropertyChanged("center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mainAccount {
            get {
                return this.mainAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.mainAccountField, value) != true)) {
                    this.mainAccountField = value;
                    this.RaisePropertyChanged("mainAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                if ((object.ReferenceEquals(this.purposeField, value) != true)) {
                    this.purposeField = value;
                    this.RaisePropertyChanged("purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                if ((this.transactionDateField.Equals(value) != true)) {
                    this.transactionDateField = value;
                    this.RaisePropertyChanged("transactionDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract))]
    public partial class XppObjectBase : OAuthTLSConsoleApplication.ServiceReference1.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMResultContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMResultContract : OAuthTLSConsoleApplication.ServiceReference1.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OAuthTLSConsoleApplication.ServiceReference1.NoYes successField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OAuthTLSConsoleApplication.ServiceReference1.NoYes success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMLedgerJournalTableContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMLedgerJournalTableContract : OAuthTLSConsoleApplication.ServiceReference1.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransBatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                if ((object.ReferenceEquals(this.centerField, value) != true)) {
                    this.centerField = value;
                    this.RaisePropertyChanged("center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransBatch {
            get {
                return this.cnaABRMTransBatchField;
            }
            set {
                if ((object.ReferenceEquals(this.cnaABRMTransBatchField, value) != true)) {
                    this.cnaABRMTransBatchField = value;
                    this.RaisePropertyChanged("cnaABRMTransBatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransSource {
            get {
                return this.cnaABRMTransSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.cnaABRMTransSourceField, value) != true)) {
                    this.cnaABRMTransSourceField = value;
                    this.RaisePropertyChanged("cnaABRMTransSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransType {
            get {
                return this.cnaABRMTransTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.cnaABRMTransTypeField, value) != true)) {
                    this.cnaABRMTransTypeField = value;
                    this.RaisePropertyChanged("cnaABRMTransType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                if ((object.ReferenceEquals(this.purposeField, value) != true)) {
                    this.purposeField = value;
                    this.RaisePropertyChanged("purpose");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMLedgerJournalTransContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMLedgerJournalTransContract : OAuthTLSConsoleApplication.ServiceReference1.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountCurCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountCurDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime documentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetTxtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountNum {
            get {
                return this.accountNumField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNumField, value) != true)) {
                    this.accountNumField = value;
                    this.RaisePropertyChanged("accountNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.accountTypeField, value) != true)) {
                    this.accountTypeField = value;
                    this.RaisePropertyChanged("accountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amountCurCredit {
            get {
                return this.amountCurCreditField;
            }
            set {
                if ((this.amountCurCreditField.Equals(value) != true)) {
                    this.amountCurCreditField = value;
                    this.RaisePropertyChanged("amountCurCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amountCurDebit {
            get {
                return this.amountCurDebitField;
            }
            set {
                if ((this.amountCurDebitField.Equals(value) != true)) {
                    this.amountCurDebitField = value;
                    this.RaisePropertyChanged("amountCurDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                if ((object.ReferenceEquals(this.centerField, value) != true)) {
                    this.centerField = value;
                    this.RaisePropertyChanged("center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransText {
            get {
                return this.cnaABRMTransTextField;
            }
            set {
                if ((object.ReferenceEquals(this.cnaABRMTransTextField, value) != true)) {
                    this.cnaABRMTransTextField = value;
                    this.RaisePropertyChanged("cnaABRMTransText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentField, value) != true)) {
                    this.departmentField = value;
                    this.RaisePropertyChanged("department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime documentDate {
            get {
                return this.documentDateField;
            }
            set {
                if ((this.documentDateField.Equals(value) != true)) {
                    this.documentDateField = value;
                    this.RaisePropertyChanged("documentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documentNum {
            get {
                return this.documentNumField;
            }
            set {
                if ((object.ReferenceEquals(this.documentNumField, value) != true)) {
                    this.documentNumField = value;
                    this.RaisePropertyChanged("documentNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice {
            get {
                return this.invoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceField, value) != true)) {
                    this.invoiceField = value;
                    this.RaisePropertyChanged("invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetAccount {
            get {
                return this.offsetAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.offsetAccountField, value) != true)) {
                    this.offsetAccountField = value;
                    this.RaisePropertyChanged("offsetAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string offsetAccountType {
            get {
                return this.offsetAccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.offsetAccountTypeField, value) != true)) {
                    this.offsetAccountTypeField = value;
                    this.RaisePropertyChanged("offsetAccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetCompany {
            get {
                return this.offsetCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.offsetCompanyField, value) != true)) {
                    this.offsetCompanyField = value;
                    this.RaisePropertyChanged("offsetCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetTxt {
            get {
                return this.offsetTxtField;
            }
            set {
                if ((object.ReferenceEquals(this.offsetTxtField, value) != true)) {
                    this.offsetTxtField = value;
                    this.RaisePropertyChanged("offsetTxt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentReferenceField, value) != true)) {
                    this.paymentReferenceField = value;
                    this.RaisePropertyChanged("paymentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                if ((object.ReferenceEquals(this.purposeField, value) != true)) {
                    this.purposeField = value;
                    this.RaisePropertyChanged("purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transDate {
            get {
                return this.transDateField;
            }
            set {
                if ((this.transDateField.Equals(value) != true)) {
                    this.transDateField = value;
                    this.RaisePropertyChanged("transDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txt {
            get {
                return this.txtField;
            }
            set {
                if ((object.ReferenceEquals(this.txtField, value) != true)) {
                    this.txtField = value;
                    this.RaisePropertyChanged("txt");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceReference1.ABRM")]
    public interface ABRM {
        
        // CODEGEN: Generating message contract since message ValidateDateDimensions has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/ValidateDateDimensions", ReplyAction="http://tempuri.org/ABRM/ValidateDateDimensionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.Fault), Action="http://tempuri.org/ABRM/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse ValidateDateDimensions(OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/ValidateDateDimensions", ReplyAction="http://tempuri.org/ABRM/ValidateDateDimensionsResponse")]
        System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse> ValidateDateDimensionsAsync(OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions request);
        
        // CODEGEN: Generating message contract since message PostJournal has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/PostJournal", ReplyAction="http://tempuri.org/ABRM/PostJournalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OAuthTLSConsoleApplication.ServiceReference1.Fault), Action="http://tempuri.org/ABRM/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse PostJournal(OAuthTLSConsoleApplication.ServiceReference1.PostJournal request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/PostJournal", ReplyAction="http://tempuri.org/ABRM/PostJournalResponse")]
        System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse> PostJournalAsync(OAuthTLSConsoleApplication.ServiceReference1.PostJournal request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDateDimensions", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ValidateDateDimensions {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract[] _validationContracts;
        
        public ValidateDateDimensions() {
        }
        
        public ValidateDateDimensions(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract[] _validationContracts) {
            this.CallContext = CallContext;
            this._validationContracts = _validationContracts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDateDimensionsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ValidateDateDimensionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public OAuthTLSConsoleApplication.ServiceReference1.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result;
        
        public ValidateDateDimensionsResponse() {
        }
        
        public ValidateDateDimensionsResponse(OAuthTLSConsoleApplication.ServiceReference1.Infolog Infolog, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostJournal", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PostJournal {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract _headerContract;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract[] _lineContracts;
        
        public PostJournal() {
        }
        
        public PostJournal(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract _headerContract, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract[] _lineContracts) {
            this.CallContext = CallContext;
            this._headerContract = _headerContract;
            this._lineContracts = _lineContracts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostJournalResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PostJournalResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public OAuthTLSConsoleApplication.ServiceReference1.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result;
        
        public PostJournalResponse() {
        }
        
        public PostJournalResponse(OAuthTLSConsoleApplication.ServiceReference1.Infolog Infolog, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ABRMChannel : OAuthTLSConsoleApplication.ServiceReference1.ABRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABRMClient : System.ServiceModel.ClientBase<OAuthTLSConsoleApplication.ServiceReference1.ABRM>, OAuthTLSConsoleApplication.ServiceReference1.ABRM {
        
        public ABRMClient() {
        }
        
        public ABRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse OAuthTLSConsoleApplication.ServiceReference1.ABRM.ValidateDateDimensions(OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions request) {
            return base.Channel.ValidateDateDimensions(request);
        }
        
        public OAuthTLSConsoleApplication.ServiceReference1.Infolog ValidateDateDimensions(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract[] _validationContracts, out OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result) {
            OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions inValue = new OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions();
            inValue.CallContext = CallContext;
            inValue._validationContracts = _validationContracts;
            OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse retVal = ((OAuthTLSConsoleApplication.ServiceReference1.ABRM)(this)).ValidateDateDimensions(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse> OAuthTLSConsoleApplication.ServiceReference1.ABRM.ValidateDateDimensionsAsync(OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions request) {
            return base.Channel.ValidateDateDimensionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensionsResponse> ValidateDateDimensionsAsync(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMValidationContract[] _validationContracts) {
            OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions inValue = new OAuthTLSConsoleApplication.ServiceReference1.ValidateDateDimensions();
            inValue.CallContext = CallContext;
            inValue._validationContracts = _validationContracts;
            return ((OAuthTLSConsoleApplication.ServiceReference1.ABRM)(this)).ValidateDateDimensionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse OAuthTLSConsoleApplication.ServiceReference1.ABRM.PostJournal(OAuthTLSConsoleApplication.ServiceReference1.PostJournal request) {
            return base.Channel.PostJournal(request);
        }
        
        public OAuthTLSConsoleApplication.ServiceReference1.Infolog PostJournal(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract _headerContract, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract[] _lineContracts, out OAuthTLSConsoleApplication.ServiceReference1.cnaABRMResultContract result) {
            OAuthTLSConsoleApplication.ServiceReference1.PostJournal inValue = new OAuthTLSConsoleApplication.ServiceReference1.PostJournal();
            inValue.CallContext = CallContext;
            inValue._headerContract = _headerContract;
            inValue._lineContracts = _lineContracts;
            OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse retVal = ((OAuthTLSConsoleApplication.ServiceReference1.ABRM)(this)).PostJournal(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse> OAuthTLSConsoleApplication.ServiceReference1.ABRM.PostJournalAsync(OAuthTLSConsoleApplication.ServiceReference1.PostJournal request) {
            return base.Channel.PostJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<OAuthTLSConsoleApplication.ServiceReference1.PostJournalResponse> PostJournalAsync(OAuthTLSConsoleApplication.ServiceReference1.CallContext CallContext, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTableContract _headerContract, OAuthTLSConsoleApplication.ServiceReference1.cnaABRMLedgerJournalTransContract[] _lineContracts) {
            OAuthTLSConsoleApplication.ServiceReference1.PostJournal inValue = new OAuthTLSConsoleApplication.ServiceReference1.PostJournal();
            inValue.CallContext = CallContext;
            inValue._headerContract = _headerContract;
            inValue._lineContracts = _lineContracts;
            return ((OAuthTLSConsoleApplication.ServiceReference1.ABRM)(this)).PostJournalAsync(inValue);
        }
    }
}
