//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapConsoleApplication.CnaAbrmIntigrationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMValidationContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMValidationContract : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mainAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transactionDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mainAccount {
            get {
                return this.mainAccountField;
            }
            set {
                this.mainAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMResultContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMResultContract : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapConsoleApplication.CnaAbrmIntigrationServiceReference.NoYes successField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.NoYes success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMLedgerJournalTableContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMLedgerJournalTableContract : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransBatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransBatch {
            get {
                return this.cnaABRMTransBatchField;
            }
            set {
                this.cnaABRMTransBatchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransSource {
            get {
                return this.cnaABRMTransSourceField;
            }
            set {
                this.cnaABRMTransSourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransType {
            get {
                return this.cnaABRMTransTypeField;
            }
            set {
                this.cnaABRMTransTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cnaABRMLedgerJournalTransContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class cnaABRMLedgerJournalTransContract : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountCurCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal amountCurDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnaABRMTransTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime documentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string documentNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string offsetTxtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime transDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string accountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amountCurCredit {
            get {
                return this.amountCurCreditField;
            }
            set {
                this.amountCurCreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amountCurDebit {
            get {
                return this.amountCurDebitField;
            }
            set {
                this.amountCurDebitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnaABRMTransText {
            get {
                return this.cnaABRMTransTextField;
            }
            set {
                this.cnaABRMTransTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime documentDate {
            get {
                return this.documentDateField;
            }
            set {
                this.documentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string documentNum {
            get {
                return this.documentNumField;
            }
            set {
                this.documentNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetAccount {
            get {
                return this.offsetAccountField;
            }
            set {
                this.offsetAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string offsetAccountType {
            get {
                return this.offsetAccountTypeField;
            }
            set {
                this.offsetAccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetCompany {
            get {
                return this.offsetCompanyField;
            }
            set {
                this.offsetCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string offsetTxt {
            get {
                return this.offsetTxtField;
            }
            set {
                this.offsetTxtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                this.paymentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string txt {
            get {
                return this.txtField;
            }
            set {
                this.txtField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="CnaAbrmIntigrationServiceReference.ABRM")]
    public interface ABRM {
        
        // CODEGEN: Generating message contract since message ValidateDateDimensions has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/ValidateDateDimensions", ReplyAction="http://tempuri.org/ABRM/ValidateDateDimensionsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://tempuri.org/ABRM/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse ValidateDateDimensions(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/ValidateDateDimensions", ReplyAction="http://tempuri.org/ABRM/ValidateDateDimensionsResponse")]
        System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse> ValidateDateDimensionsAsync(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions request);
        
        // CODEGEN: Generating message contract since message PostJournal has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/PostJournal", ReplyAction="http://tempuri.org/ABRM/PostJournalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://tempuri.org/ABRM/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse PostJournal(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ABRM/PostJournal", ReplyAction="http://tempuri.org/ABRM/PostJournalResponse")]
        System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse> PostJournalAsync(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDateDimensions", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ValidateDateDimensions {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMValidationContract[] _validationContracts;
        
        public ValidateDateDimensions() {
        }
        
        public ValidateDateDimensions(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMValidationContract[] _validationContracts) {
            this.CallContext = CallContext;
            this._validationContracts = _validationContracts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateDateDimensionsResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class ValidateDateDimensionsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result;
        
        public ValidateDateDimensionsResponse() {
        }
        
        public ValidateDateDimensionsResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostJournal", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PostJournal {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTableContract _headerContract;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTransContract[] _lineContracts;
        
        public PostJournal() {
        }
        
        public PostJournal(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTableContract _headerContract, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTransContract[] _lineContracts) {
            this.CallContext = CallContext;
            this._headerContract = _headerContract;
            this._lineContracts = _lineContracts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostJournalResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class PostJournalResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result;
        
        public PostJournalResponse() {
        }
        
        public PostJournalResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ABRMChannel : SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABRMClient : System.ServiceModel.ClientBase<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM>, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM {
        
        public ABRMClient() {
        }
        
        public ABRMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABRMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABRMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABRMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM.ValidateDateDimensions(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions request) {
            return base.Channel.ValidateDateDimensions(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog ValidateDateDimensions(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMValidationContract[] _validationContracts, out SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result) {
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions inValue = new SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions();
            inValue.CallContext = CallContext;
            inValue._validationContracts = _validationContracts;
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse retVal = ((SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM)(this)).ValidateDateDimensions(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse> SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM.ValidateDateDimensionsAsync(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions request) {
            return base.Channel.ValidateDateDimensionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensionsResponse> ValidateDateDimensionsAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMValidationContract[] _validationContracts) {
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions inValue = new SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ValidateDateDimensions();
            inValue.CallContext = CallContext;
            inValue._validationContracts = _validationContracts;
            return ((SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM)(this)).ValidateDateDimensionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM.PostJournal(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal request) {
            return base.Channel.PostJournal(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog PostJournal(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTableContract _headerContract, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTransContract[] _lineContracts, out SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMResultContract result) {
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal inValue = new SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal();
            inValue.CallContext = CallContext;
            inValue._headerContract = _headerContract;
            inValue._lineContracts = _lineContracts;
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse retVal = ((SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM)(this)).PostJournal(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse> SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM.PostJournalAsync(SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal request) {
            return base.Channel.PostJournalAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournalResponse> PostJournalAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTableContract _headerContract, SoapConsoleApplication.CnaAbrmIntigrationServiceReference.cnaABRMLedgerJournalTransContract[] _lineContracts) {
            SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal inValue = new SoapConsoleApplication.CnaAbrmIntigrationServiceReference.PostJournal();
            inValue.CallContext = CallContext;
            inValue._headerContract = _headerContract;
            inValue._lineContracts = _lineContracts;
            return ((SoapConsoleApplication.CnaAbrmIntigrationServiceReference.ABRM)(this)).PostJournalAsync(inValue);
        }
    }
}
